/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TemperatureLazyImport = createFileRoute('/temperature')()
const LoginLazyImport = createFileRoute('/login')()
const LinksLazyImport = createFileRoute('/links')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TemperatureLazyRoute = TemperatureLazyImport.update({
  path: '/temperature',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/temperature.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const LinksLazyRoute = LinksLazyImport.update({
  path: '/links',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/links.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/links': {
      preLoaderRoute: typeof LinksLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/temperature': {
      preLoaderRoute: typeof TemperatureLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  LinksLazyRoute,
  LoginLazyRoute,
  TemperatureLazyRoute,
])

/* prettier-ignore-end */
